### ISSUE TITLE
Arduino simualtor pages - 😀 - from Wokwi Arduino simulator

### ISSUE THREAD

**Issue by matititam** [InfectedBytes/ArduinoShiftIn#2]
Hi There

Good day

Thank you for the wonderful library. I was quite excited to see it work on the first go. 
Here is the link: https://wokwi.com/arduino/projects/309541392694116928
 
![Wokwi Arduino Simulator - Shift Registers2](https://user-images.githubusercontent.com/68117142/132995793-4cccabf1-2f5e-4f94-bd90-2e7fda59c4d4.gif)

I would love to hear your feedback. We would be glad if we can also have a link in the ReadMe file for the readers of the ArduinoShiftIn library. 

Wokwi Arduino simulator is free for all. Kindly feel free to share your feedback - https://wokwi.com

Thank you!

**Comment by InfectedBytes** [comment]
Thanks! Sure thing, I added a link to your awesome simulator!

**Comment by matititam** [comment]
Thank you. that's awesome. I will share the link for the other projects shortly. Will be glad to hear feedback on the simulator.
