### ISSUE TITLE
How to get the serial output values and write if else statenent 

### ISSUE THREAD

**Issue by VarunKumaran** [InfectedBytes/ArduinoShiftIn#3]
Hiii there.... This is really an awesome library and got it work in a few mins.. but i am newbie and I wanna write an if else code from the serial output value from the serial output monitor.. like 
If ( x = 00000001); 
  Then something happens

Can you please help me out.. it would be a great help for me..

**Comment by InfectedBytes** [comment]
I'm not sure what you mean, maybe this helps?
```
#include <ShiftIn.h>

ShiftIn<1> shift;

void setup() {
  Serial.begin(9600);
  shift.begin(8, 9, 11, 12);
}

void loop() {
  if(shift.update()) { // we know some button has changed
    // you could check for specific buttons:
    if(shift.state(0)) {
      // button 0 is pressed
    } else {
      // button 0 is not pressed
    }
    // or you could also check for many buttons at once:
    if(shift.getCurrent() == 0b00000011) {
      // button 0 and 1 are pressed, button 2 to 7 are not pressed
    }
  }
  delay(1);
}
```

**Comment by VarunKumaran** [comment]
Thank you soo much this... This is exactly what I need... I am trying make a 16 channel RF remote control using microcontroller and now it is possible thanks to you.. ,😁🔥

> I'm not sure what you mean, maybe this helps?
> 
> ```
> #include <ShiftIn.h>
> 
> ShiftIn<1> shift;
> 
> void setup() {
>   Serial.begin(9600);
>   shift.begin(8, 9, 11, 12);
> }
> 
> void loop() {
>   if(shift.update()) { // we know some button has changed
>     // you could check for specific buttons:
>     if(shift.state(0)) {
>       // button 0 is pressed
>     } else {
>       // button 0 is not pressed
>     }
>     // or you could also check for many buttons at once:
>     if(shift.getCurrent() == 0b00000011) {
>       // button 0 and 1 are pressed, button 2 to 7 are not pressed
>     }
>   }
>   delay(1);
> }
> ```
